services:
  db:
    image: postgres:15-alpine
    container_name: 'db'
    restart: always
    environment:
      POSTGRES_USER: notification-service
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: notification-service
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  zk-service:
    image: bitnami/zookeeper:3.7.1
    hostname: zk-service
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JVMFLAGS: -server -Xms25m -Xmx512m -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExplicitGCInvokesConcurrent
  kafka-zk:
    image: bitnami/zookeeper:3.7.1
    hostname: kafka-zk
    ports:
      - "2183:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JVMFLAGS: -server -Xms25m -Xmx512m -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExplicitGCInvokesConcurrent
  kafka:
    image: wurstmeister/kafka:2.13-2.6.3
    depends_on:
      - kafka-zk
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zk:2181
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10000012
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 10000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 5
      LOG4J_LOGGER_ORG: WARN,STDOUT
      LOG4J_LOGGER_ORG_APACHE_KAFKA: WARN,STDOUT
      LOG4J_LOGGER_KAFKA: WARN,STDOUT
      KAFKA_JVM_PERFORMANCE_OPTS: -server -Xms25m -Xmx512m -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExplicitGCInvokesConcurrent
      KAFKA_CREATE_TOPICS: "notification-service.send:1:1,twTasks.notification-service.executeTask.default:1:1"

volumes:
  pgdata: